### ISSUE TITLE
缺少opensearch以往版本的ik分词器

### ISSUE THREAD

**Issue by KetsuZhang** [infinilabs/analysis-ik#1047]
在 https://release.infinilabs.com/analysis-ik/stable/  中只包含2.12.0版本的分词器，没有以往版本的分词器。
希望能够添加opensearch2.11.0版本的ik分词器，非常感谢！
<img width="1025" alt="fe28187164783a8c1571715506bb3fe" src="https://github.com/infinilabs/analysis-ik/assets/43643560/84476a39-6a57-418c-874d-614f1fd890c7">

**Comment by medcl** [comment]
嗯，没问题的

**Comment by KetsuZhang** [comment]
> 嗯，没问题的

非常非常感谢！

**Comment by liukuijun666** [comment]
已添加
<img width="1314" alt="image" src="https://github.com/infinilabs/analysis-ik/assets/16410456/4fe37fca-40b6-4f63-8963-f9ccf0fa672c">

**Comment by KetsuZhang** [comment]
> 已添加 <img alt="image" width="1314" src="https://private-user-images.githubusercontent.com/16410456/317659143-4fe37fca-40b6-4f63-8963-f9ccf0fa672c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MTY0NjksIm5iZiI6MTcxMTYxNjE2OSwicGF0aCI6Ii8xNjQxMDQ1Ni8zMTc2NTkxNDMtNGZlMzdmY2EtNDBiNi00ZjYzLTg5NjMtZjljY2YwZmE2NzJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDA4NTYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1ZTA4ZWI1NWVlNGQ4NGZiNWU0YjRhYTI1ZDM5MjhjNmMyMjFkZmQ2ZDAwODk0M2VlMmUwNmIyZjVhZDgwOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ru4u2IMt-T9loPGwEKmkR2Fgvb457MBDq-dIexhQaV0">

看到了，nice
