### ISSUE TITLE
如何修改 analysis-ik 支持的 Elasticsearch版本号？

### ISSUE THREAD

**Issue by broadcast98** [infinilabs/analysis-ik#1049]
"elasticsearch"版本是 "8.13.1"
下载了 analysis-ik 8.12.2.
如何将 analysis-ik 8.12.2. 修改为支持elasticsearch "8.13.1"

**Comment by TOPSAILL** [comment]
同问 感觉可以等8.13.1版本

**Comment by KouShenhai** [comment]
改一下pom里面的版本号就行啦
最简单的方式就是，用IDEA打开项目，然后全局搜索8.12.2，然后替换成8.13.1

**Comment by peer44** [comment]
找一个相近的版本，解压到plugin目录下面，改一下plugin-descriptor.properties里面的版本号就可以用了
