### ISSUE TITLE
希望提供8.13.2、7.17.19版本插件

### ISSUE THREAD

**Issue by cuiweiqiang** [infinilabs/analysis-ik#1050]

**Comment by liukuijun666** [comment]
https://release.infinilabs.com/analysis-ik/stable/elasticsearch-analysis-ik-7.17.19.zip
https://release.infinilabs.com/analysis-ik/stable/elasticsearch-analysis-ik-8.13.2.zip

**Comment by cuiweiqiang** [comment]
> https://release.infinilabs.com

多谢。
