### ISSUE TITLE
ik for 7.17.22

### ISSUE THREAD

**Issue by youxihu** [infinilabs/analysis-ik#1064]
May I ask when the 1.17.22 version of the ik plugin will be released？

**Comment by peer44** [comment]
https://release.infinilabs.com/analysis-ik/stable/
here you can get any version

**Comment by youxihu** [comment]
> https://release.infinilabs.com/analysis-ik/stable/ here you can get any version
Thank you very much. It's so efficient

**Comment by wupan0820** [comment]
发布包里面缺少7.17.22版本的源码，是否可以帮忙提供下下载的地址来着
