### ISSUE TITLE
求 v8.10.0

### ISSUE THREAD

**Issue by weiwancheng** [infinilabs/analysis-ik#1078]
搜了一圈没有v8.10.0 版本的，求v8.10.0版本

**Comment by liukuijun666** [comment]
Here: https://release.infinilabs.com/analysis-ik/stable/elasticsearch-analysis-ik-8.10.0.zip
<img width="1435" alt="image" src="https://github.com/user-attachments/assets/ad5a1bbd-506d-42f8-92db-73978800cebe">
